name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Automatic semantic version bump (major/minor/patch from commit messages)
      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@v11.0.3
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      # Generate changelog file from previous commits
      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v5
        id: changelog
        with:
          mode: "PR"
          fetchReleaseInformation: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}} #{{CONTRIBUTORS}}",
              "pr_template": "#{{URL}} #{{TITLE}} #{{PR_NUMBER}}",
              "categories": [
                {
                    "title": "## Improvements",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## Bug Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## Housekeeping",
                    "labels": []
                }
              ],
              "sort": {
                    "order": "ASC",
                    "on_property": "mergedAt"
              },
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ],
            }
          toTag: ${{ steps.bump_version.outputs.newTag }}
          fromTag: ""

      # Create automatic GitHub release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: "${{ secrets.RELEASE_PLEASE_TOKEN }}"
          tag: ${{ steps.bump_version.outputs.newTag }}
          prerelease: false
          name: "Release ${{ steps.bump_version.outputs.newTag }}-beta"
          body: |
            ${{ steps.changelog.outputs.changelog }}

            ![release-image](https://raw.githubusercontent.com/steel-dev/.github/refs/heads/main/profile/github_hero.png)

            ## Come Hang Out
            Questions? Join us on [Discord](https://discord.gg/your-server-link)
            Found a bug? Open an issue on [GitHub](https://github.com/your-repo/issues)

            ${{ steps.changelog.outputs.contributors }}
